# Site settings
name: Brian Buccola
description: "Brian Buccola's website"
url: http://brianbuccola.com
author:
  name: Brian Buccola
  uri: http://brianbuccola.com/

# Publishing settings
permalink: /:title/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-feed

# Defaults
defaults:
  -
    scope:
      path: ""            # empty string means all files
      type: "posts"       # limit to files in `_posts`
    values:
      comments: "true"    # set `comments` to `true` by default for all posts
