# Site settings
title: Brian Buccola

# Publishing settings
permalink: /:title/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-feed
