# Site settings
title: Brian Buccola

# Publishing settings
permalink: /:title/

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
