# Site settings
name: Brian Buccola
description: "Brian Buccola's website"
url: http://brianbuccola.com
author:
  name: Brian Buccola
  email: brian.buccola@gmail.com
  uri: http://brianbuccola.com/

# Publishing settings
permalink: /:title/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-feed
