# Site settings
title: Brian Buccola
description: Brian Buccola is a linguist who specializes in formal and experimental semantics and pragmatics. He also blogs about language, logic, and Linux.
url: http://brianbuccola.com
author:
  name: Brian Buccola
  uri: http://brianbuccola.com/

# Repository (suppresses error message)
repository: brianbuccola/brianbuccola.github.io

# Publishing settings
permalink: /:title/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap

# Defaults
defaults:
  -
    scope:
      path: ""            # empty string means all files
      type: "posts"       # limit to files in `_posts`
    values:
      comments: "true"    # set `comments` to `true` by default for all posts
